import { mkdir, writeFile } from 'node:fs/promises';

import { runCompatibility } from '../test/compat/harness.ts';

const results = runCompatibility();
const codes = ['same', 'reject', 'structural', 'import-only', 'n/a', 'deferred-uncovered', 'gap-uncovered', 'fail'];
const counts = new Map(codes.map((code) => [code, results.filter((result) => result.status === code).length]));
const attention = results.filter((result) => result.status === 'deferred-uncovered' || result.status === 'gap-uncovered' || result.status === 'fail');

const lines = [
  '# CommonMark / GFM compatibility report',
  '',
  '> Generated by `bun run compat:report`; do not edit totals by hand.',
  '',
  '| Classification | Cases |',
  '|---|---:|',
  ...codes.map((code) => `| \`${code}\` | ${counts.get(code)} |`),
  `| **total** | **${results.length}** |`,
  '',
  '## Deferred, uncovered, and failed cases',
  '',
];

if (attention.length === 0) lines.push('None.');
else for (const result of attention) {
  const id = result.case.example === undefined ? result.case.id : `CommonMark ${result.case.example}`;
  lines.push(`- **${id} — ${result.case.section} — ${result.status}:** ${result.observation}`);
}
lines.push('');

const output = new URL('../test/compat/reports/latest.md', import.meta.url);
await mkdir(new URL('./', output), { recursive: true });
await writeFile(output, `${lines.join('\n')}\n`, 'utf8');
console.log(`Wrote ${output.pathname}`);
