import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import test from 'node:test';

import { format, parse, semanticDocumentEquals, validate } from '../../src/index.js';
import { CHILD_KEYS, migrateV053, type MigrationDiagnostic, type MigrationDiagnosticCategory } from '../../tools/migrate/index.js';
import { parse as legacyParse } from '../../tools/migrate/legacy/parser.js';

/**
 * The v0.5.3 -> 0.1.0 migration evolution gate (audit #5). It proves that the
 * migration of the previous line's valid conformance corpus loses nothing
 * *silently*:
 *
 *  1. every case migrates to a valid 0.1.0 document, or carries an explicit
 *     `dropped` / `unrepresentable` / `review` diagnostic;
 *  2. a non-parseable result names a construct-level obstruction, never only
 *     the generic "no byte-stable surface" fallback;
 *  3. no v0.5.3 construct present in the source (re-parsed with the vendored
 *     legacy parser, mapped to its 0.1.0 name) vanishes from the migrated AST
 *     without a diagnostic;
 *  4. every meaning-preserving (`mapped`) migration round-trips through the
 *     strict parser unchanged.
 *
 * The corpus is a frozen `{id, specRef, input}` snapshot
 * (`test/migrate/v053-corpus/`, regenerated by `scripts/vendor-v053-corpus.mjs`)
 * so the gate survives the 0.1.0 freeze after which `../monorepo` may be
 * removed. The vendored legacy parser lives in `tools/migrate/legacy/`. The
 * summary table is written to `docs/audits/migration-evolution-gate.md`.
 */
interface Case {
  readonly id: string;
  readonly specRef: string;
  readonly input: string;
}

const corpus = (JSON.parse(
  readFileSync(resolve('test/migrate/v053-corpus/cases.json'), 'utf8'),
) as { readonly cases: Case[] }).cases;

const provenance = JSON.parse(
  readFileSync(resolve('test/migrate/v053-corpus/provenance.json'), 'utf8'),
) as { readonly caseCount: number; readonly inputsSha256: string };

assert.equal(corpus.length, provenance.caseCount, 'snapshot case count matches provenance');
assert.ok(corpus.length > 200, `expected the full valid v0.5.3 corpus, found ${corpus.length}`);

const LOSS: readonly MigrationDiagnosticCategory[] = ['dropped', 'unrepresentable', 'review'];
type Bucket = 'clean' | MigrationDiagnosticCategory;

/** v0.4.0 (v0.5.3) node type -> its 0.1.0 equivalent, where the name changed.
 * These are the only structural renames in the corpus (the reviewer confirmed
 * the set); `download` is an attribute value, not a node type. */
const EQUIVALENT: Readonly<Record<string, string>> = {
  strike: 'deletion',
  span: 'metadataSpan',
  directiveContainer: 'container',
  fencedContainer: 'container',
};
/** Only genuine non-nodes / recovery scaffolding. `softBreak` / `hardBreak` are
 * NOT exempt: A6 removes the parser *profile*, not the constructs — a vanished
 * break must be explained by a specific diagnostic like any other loss. */
const COVERAGE_EXEMPT = new Set(['document', 'recoveryDocument', 'errorBlock']);
/** Enclosing types whose content-transformation diagnostic covers a vanished child. */
const WRAPPER_TYPES = new Set(['list', 'listItem', 'container', 'directiveContainer', 'fencedContainer', 'quoteRegion', 'table', 'tableRow']);
/** Descendant types whose whole-line promotion legitimately dissolves an enclosing `paragraph`. */
const CARRIER_TYPES = new Set(['link', 'inlineImage', 'imageBlock', 'videoBlock', 'audioBlock', 'embedBlock', 'downloadBlock', 'directiveContainer', 'fencedContainer']);

/** True for a migrator fallback that names no construct at all. */
function isGeneric(message: string): boolean {
  return message.includes('is not byte-idempotent under the 0.1.0 formatter') ||
    message.includes('the migrated surface parses but is not byte-stable') ||
    message === 'the migrated document has no byte-stable 0.1.0 surface — review the diagnostics above' ||
    /could not be formatted: (cannot format document|unknown)$/u.test(message) ||
    message === 'no 0.1.0 canonical surface: the block composition has no 0.1.0 canonical surface';
}

/** Recursive set of node `type`s, following real child positions only. */
function typeSet(node: unknown, into = new Set<string>()): Set<string> {
  if (node === null || typeof node !== 'object') return into;
  if (Array.isArray(node)) { for (const item of node) typeSet(item, into); return into; }
  const record = node as Record<string, unknown>;
  if (typeof record['type'] === 'string') into.add(record['type']);
  for (const [key, value] of Object.entries(record)) if (CHILD_KEYS.has(key)) typeSet(value, into);
  return into;
}

/** For each node type in a legacy AST, its ancestor and descendant type sets. A
 * diagnosed structural transformation restructures a contiguous root→leaf
 * region, so a wrapper is "named" when the diagnostic names anything on its
 * path (a `paragraph` that becomes a `downloadBlock` is covered by "whole-line
 * download link → downloadBlock"). */
function relatedTypes(node: unknown): { ancestors: Map<string, Set<string>>; descendants: Map<string, Set<string>> } {
  const ancestors = new Map<string, Set<string>>();
  const descendants = new Map<string, Set<string>>();
  const walk = (value: unknown, chain: readonly string[]): Set<string> => {
    const below = new Set<string>();
    if (value === null || typeof value !== 'object') return below;
    if (Array.isArray(value)) {
      for (const item of value) for (const type of walk(item, chain)) below.add(type);
      return below;
    }
    const record = value as Record<string, unknown>;
    const here = typeof record['type'] === 'string' ? record['type'] : undefined;
    const nextChain = here === undefined ? chain : [...chain, here];
    for (const [key, child] of Object.entries(record)) {
      if (CHILD_KEYS.has(key)) for (const type of walk(child, nextChain)) below.add(type);
    }
    if (here !== undefined) {
      const anc = ancestors.get(here) ?? new Set<string>();
      for (const type of chain) anc.add(type);
      ancestors.set(here, anc);
      const desc = descendants.get(here) ?? new Set<string>();
      for (const type of below) desc.add(type);
      descendants.set(here, desc);
      below.add(here);
    }
    return below;
  };
  walk(node, []);
  return { ancestors, descendants };
}

/** The single-space placeholder the migrator inserts when a structure lost all content. */
function containsPlaceholder(node: unknown): boolean {
  if (node === null || typeof node !== 'object') return false;
  const record = node as Record<string, unknown>;
  const first = Array.isArray(record['children']) ? (record['children'][0] as Record<string, unknown> | undefined) : undefined;
  if (
    record['type'] === 'paragraph' && Array.isArray(record['children']) && record['children'].length === 1 &&
    first?.['type'] === 'text' && first['value'] === ' '
  ) return true;
  return Object.values(record).some((value) =>
    Array.isArray(value) ? value.some(containsPlaceholder) : containsPlaceholder(value));
}

interface Outcome {
  readonly id: string;
  readonly bucket: Bucket;
  readonly parses: boolean;
  readonly failures: readonly string[];
}

const outcomes: Outcome[] = corpus.map((testCase) => {
  const failures: string[] = [];
  const result = migrateV053(testCase.input);
  const categories = new Set(result.diagnostics.map((diagnostic) => diagnostic.category));
  const diagnostics: readonly MigrationDiagnostic[] = result.diagnostics;
  const hasLossDiagnostic = LOSS.some((category) => categories.has(category));
  const diagnosticText = diagnostics.map((diagnostic) => diagnostic.message).join(' ‖ ');

  const parsed = parse(result.text);
  const parses = parsed.status === 'ok' && result.text.length > 0;

  // (1) valid 0.1.0 document, or an explicit loss diagnostic.
  if (!(parses || hasLossDiagnostic)) {
    failures.push(`neither a valid 0.1.0 document nor a loss diagnostic (parse ${parsed.status})`);
  }

  // (2) every `unrepresentable` diagnostic must name a construct-level
  // obstruction — a generic one fails the gate regardless of any accompanying
  // (e.g. `mapped`) diagnostic.
  for (const diagnostic of diagnostics) {
    if (diagnostic.category === 'unrepresentable' && isGeneric(diagnostic.message)) {
      failures.push(`generic \`unrepresentable\` diagnostic: "${diagnostic.message}"`);
    }
  }

  if (parsed.status === 'ok' && result.text.length > 0) {
    const validation = validate(parsed.document);
    if (validation.status !== 'ok') {
      failures.push(`migrated document fails validate: ${JSON.stringify(validation.diagnostics[0] ?? validation.status)}`);
    }
    if (containsPlaceholder(parsed.document) && !hasLossDiagnostic) {
      failures.push('placeholder paragraph without a loss diagnostic');
    }
  }

  // (3) construct coverage — every source construct that is missing from the
  // migrated AST must be named by a diagnostic (or the case is non-parseable,
  // covered by 1/2). A diagnostic about construct A does not excuse construct B.
  let legacyRoot: unknown;
  try { legacyRoot = legacyParse(testCase.input, { errorRecovery: false }); } catch { /* covered by (1) */ }
  const legacyTypes = typeSet(legacyRoot);
  const { ancestors, descendants } = relatedTypes(legacyRoot);
  const migratedTypes = parsed.status === 'ok' ? typeSet(parsed.document) : new Set<string>();
  const lowerText = diagnosticText.toLowerCase();
  if (parsed.status === 'ok' && result.text.length > 0) {
    for (const legacy of legacyTypes) {
      const expected = EQUIVALENT[legacy] ?? legacy;
      if (COVERAGE_EXEMPT.has(expected) || migratedTypes.has(expected)) continue;
      // A missing type is covered when a diagnostic names it, its 0.1.0
      // equivalent, an *enclosing wrapper* whose content transformation the
      // diagnostic describes (a `review` covers `list`+`listItem`+`paragraph`
      // when a definition list folds to a caption), or a *carrier descendant*
      // whose whole-line promotion dissolves the wrapper (a `link` →
      // `downloadBlock` covers its enclosing `paragraph`). `document` and
      // leaf/atom types never bridge.
      const names = new Set<string>([legacy, expected]);
      for (const ancestor of ancestors.get(legacy) ?? []) if (WRAPPER_TYPES.has(ancestor)) names.add(ancestor);
      for (const descendant of descendants.get(legacy) ?? []) if (CARRIER_TYPES.has(descendant)) names.add(descendant);
      for (const related of [...names]) names.add(EQUIVALENT[related] ?? related);
      if (['span', 'metadataSpan'].includes(expected)) names.add('metadata span');
      if (legacy === 'hardBreak') { names.add('hard break'); names.add('line break'); }
      const named = [...names].some((word) => word.length > 2 && lowerText.includes(word.toLowerCase()));
      if (!named) failures.push(`construct "${legacy}" dropped from the migrated AST without a diagnostic that names it or a wrapper/carrier on its path`);
    }
  }

  // (4) meaning-preserving migrations round-trip through strict.
  const mappedOnly = diagnostics.length > 0 &&
    diagnostics.every((diagnostic) => diagnostic.category === 'mapped');
  if (mappedOnly && parsed.status === 'ok' && result.text.length > 0) {
    const formatted = format(parsed.document);
    if (formatted.status !== 'ok') failures.push('mapped output does not format');
    else {
      const strict = parse(formatted.source, { strict: true });
      if (strict.status !== 'ok') failures.push('mapped canonical is not strict-valid');
      else {
        const equality = semanticDocumentEquals(parsed.document, strict.document);
        if (equality.status !== 'ok' || !equality.equal) failures.push('mapped migration does not round-trip');
      }
    }
  }

  const bucket: Bucket = categories.has('unrepresentable') ? 'unrepresentable'
    : categories.has('dropped') ? 'dropped'
    : categories.has('review') ? 'review'
    : categories.has('mapped') ? 'mapped'
    : 'clean';

  return { id: testCase.id, bucket, parses, failures };
});

for (const outcome of outcomes) {
  test(`v0.5.3 -> 0.1.0 evolution: ${outcome.id}`, () => {
    assert.deepEqual(outcome.failures, [], `${outcome.id}: ${outcome.failures.join('; ')}`);
  });
}

test('write docs/audits/migration-evolution-gate.md', () => {
  const count = (bucket: Bucket): number => outcomes.filter((outcome) => outcome.bucket === bucket).length;
  const cleanParse = outcomes.filter((outcome) => outcome.parses).length;
  const emptyOrInvalid = outcomes.filter((outcome) => !outcome.parses).length;
  const parseShift = outcomes.filter((outcome) => outcome.parses && outcome.bucket === 'unrepresentable').length;

  const lines = [
    '# Migration evolution gate — v0.5.3 → 0.1.0',
    '',
    '> Regenerated by `test/migrate/migration-evolution-gate.test.ts`. Do not edit by hand.',
    '',
    `Source corpus: \`test/migrate/v053-corpus/\` (frozen snapshot, sha256 \`${provenance.inputsSha256.slice(0, 16)}…\`).`,
    `Each of the ${corpus.length} valid v0.5.3 cases migrates to a valid 0.1.0 document **or** carries an explicit`,
    '`dropped` / `unrepresentable` / `review` diagnostic that names a construct-level obstruction; no v0.5.3',
    'construct vanishes from the migrated AST without a diagnostic; every `mapped` migration round-trips.',
    '',
    '| Outcome | Cases |',
    '|---|---:|',
    `| clean (no diagnostic, valid 0.1.0) | ${count('clean')} |`,
    `| \`mapped\` (rewritten, round-trips) | ${count('mapped')} |`,
    `| \`review\` (meaning-changing rewrite flagged) | ${count('review')} |`,
    `| \`dropped\` (obsolete field/node removed) | ${count('dropped')} |`,
    `| \`unrepresentable\` (no 0.1.0 form; kept local or removed) | ${count('unrepresentable')} |`,
    `| **total** | **${corpus.length}** |`,
    '',
    `Migrated output: ${cleanParse} / ${corpus.length} parse to a valid, non-empty 0.1.0 document ` +
      `(${parseShift} of them parse but not back to the intended tree); ${emptyOrInvalid} have no valid ` +
      'non-empty output (empty, or an invalid surface). Every case outside "clean" / "mapped" carries a ' +
      'construct-level named diagnostic; no `unrepresentable` diagnostic is generic.',
    '',
  ];
  writeFileSync(resolve('docs/audits/migration-evolution-gate.md'), `${lines.join('\n')}\n`);
});
